### ISSUE TITLE
This is not an issue

### ISSUE THREAD

**Issue by lewisdiamond** [xStrom/compare#1]
Sorry to reach out to you via GitHub issues, I could not find a better way.

My collaborators and I wrote a stream library for NodeJS which we'd like to call `strom`.  Since you currently hold the `strom` org on npmjs.com, I was wondering if you still used it actively and if not, if you'd be willing to transfer it to us.

You can find the code here: https://git.lewis.id/strom/strom/src/branch/dev

Thanks,
Lewis

**Comment by xStrom** [comment]
Hey Lewis,

Sorry for the late reply, I've been away for the summer.

So yes I use npm basically daily, although I haven't published any popular packages.
Still, I would like to hang on to my name if possible.

I know that can suck for you guys. I'm well aware, as evidenced by me having to use **xStrom** here on GitHub.
